// app.js — ported from academia.html. See
// /root/.claude/plans/your-job-is-to-iterative-trinket.md §H1 for the exact
// line-by-line map this file follows, and
// /root/gg-arena-vibe-2/entrainement-handoff/S4-notes.md for the
// classification (byte-for-byte / one enumerated change / rewrite) of every
// function below.
//
// No wrapping IIFE, on purpose: academia.html's original <script> block was
// plain top-level `function` declarations, which is exactly what makes them
// reachable as globals for the inline onclick="..."/oninput="..." handlers
// generated by renderDay(). Node's CommonJS loader gives this same file its
// own module scope automatically when required by tests, so no IIFE is
// needed for that side either.

// --- API bridge: window globals in the browser, require() under node --test.
// New code (not from academia.html) — the old app had no client-side auth or
// Sheets client, the server held both. Guarded so require('./app.js') under
// node never throws, per H3.
var SheetsAPI = (typeof window !== 'undefined' && window.Sheets) ? window.Sheets :
    (typeof require === 'function' ? (function () { try { return require('./sheets.js'); } catch (e) { return null; } })() : null);
var AuthAPI = (typeof window !== 'undefined' && window.Auth) ? window.Auth :
    (typeof require === 'function' ? (function () { try { return require('./auth.js'); } catch (e) { return null; } })() : null);

var sheetsClient = null;
if (SheetsAPI && typeof SheetsAPI.createClient === 'function') {
    try {
        sheetsClient = SheetsAPI.createClient({
            // Per S3-notes.md: sheets.js's default onAuthFailure bridge
            // calls Auth.handleAuthFailure() with no appState, which loses
            // the active tab + scroll restore on a mid-session 401/403.
            // Pass a closure carrying the current appState instead.
            onAuthFailure: function () {
                return AuthAPI ? AuthAPI.handleAuthFailure(undefined, currentAppState()) : undefined;
            }
        });
    } catch (e) {
        // No storage/fetch available (e.g. under node --test with no
        // window/localStorage) — sheetsClient stays null, only the pure
        // functions (parseDays/injectPastComments/renderDay) are testable
        // there, which is exactly H3's requirement.
        sheetsClient = null;
    }
}

// Restore the pre-redirect active tab + scroll after the OAuth round trip
// (auth.js stashes/returns this as `appState`; academia.html never had this
// concept since the old server held the session). New code.
function currentAppState() {
    var tab = 'treino';
    if (typeof document !== 'undefined') {
        var activeTabBtn = document.querySelector('.tab.active');
        if (activeTabBtn) {
            var onclickAttr = activeTabBtn.getAttribute('onclick') || '';
            var m = onclickAttr.match(/switchTab\('([^']+)'/);
            if (m) tab = m[1];
        }
    }
    var scroll = (typeof window !== 'undefined' && typeof window.scrollY === 'number') ? window.scrollY : 0;
    return { tab: tab, scroll: scroll };
}

function restoreAppState(appState) {
    if (!appState || typeof document === 'undefined') return;
    if (appState.tab && appState.tab !== 'treino') {
        var btn = document.querySelector('.tab[onclick*="switchTab(\'' + appState.tab + '\'"]');
        if (btn) switchTab(appState.tab, btn);
    }
    if (typeof appState.scroll === 'number' && typeof window !== 'undefined' && window.scrollTo) {
        window.scrollTo(0, appState.scroll);
    }
}

// --- Token freshness on writes + pending-write replay ------------------
// New code (not from academia.html — the old app's server held the
// credential, so a browser-side token could never go stale mid-session).
//
// The OAuth implicit flow has no refresh token, and Google's authorization
// endpoint refuses to render in an iframe, so the ONLY way to renew the
// 1 h access token is a top-level prompt=none redirect. That is why an edit
// made after the token expired used to surface as an "auth failure" alert
// and lose the typed value: sheets.js fired the redirect from inside the
// PUT, and the in-flight edit died with the page.
//
// So every write now checks the token BEFORE it goes out. If the token is
// gone or expired, the edit is parked in sessionStorage (which survives the
// round trip to Google), the silent renewal is started, and the queue is
// replayed on the way back in — the user sees a brief reflow instead of an
// error, and the value lands.

var PENDING_WRITES_KEY = 'entr.pendingWrites';

// RPE always lives in column O (index 14) — same constant sheets.js pins
// updateRPE to. Only used here to give a parked RPE write a target key that
// can be de-duplicated against the other writes on that row.
var RPE_COL_INDEX = (SheetsAPI && typeof SheetsAPI.RPE_COLUMN_INDEX === 'number') ? SheetsAPI.RPE_COLUMN_INDEX : 14;

function pendingWritesStorage() {
    try {
        return (typeof window !== 'undefined' && window.sessionStorage) ? window.sessionStorage : null;
    } catch (e) {
        return null; // Safari private mode / storage disabled
    }
}

function readPendingWrites() {
    var storage = pendingWritesStorage();
    if (!storage) return [];
    var raw = storage.getItem(PENDING_WRITES_KEY);
    if (!raw) return [];
    try {
        var parsed = JSON.parse(raw);
        return Array.isArray(parsed) ? parsed : [];
    } catch (e) {
        return [];
    }
}

function writePendingWrites(list) {
    var storage = pendingWritesStorage();
    if (!storage) return;
    if (!list || list.length === 0) storage.removeItem(PENDING_WRITES_KEY);
    else storage.setItem(PENDING_WRITES_KEY, JSON.stringify(list));
}

function samePendingTarget(a, b) {
    return a.kind === b.kind && a.sheetName === b.sheetName &&
        a.rowIndex === b.rowIndex && a.colIndex === b.colIndex;
}

// Queues one write, de-duplicated on (kind, sheet, row, col) so a field
// edited twice before the redirect replays only its latest value.
function queuePendingWrite(entry) {
    if (!entry) return;
    var list = readPendingWrites().filter(function (w) {
        return !samePendingTarget(w, entry);
    });
    list.push(entry);
    writePendingWrites(list);
}

// Renders the "Connexion à Google requise. [Se reconnecter]" prompt into
// the given error element. Shared by the load path and the write path so
// both dead ends look the same.
function renderReconnectPrompt(errorEl) {
    if (typeof document === 'undefined' || !AuthAPI) return;
    var error = errorEl || document.getElementById('error');
    if (!error) return;
    error.textContent = '';
    var msg = document.createElement('span');
    msg.textContent = AuthAPI.MESSAGES.SIGN_IN_REQUIRED + '. ';
    var btn = document.createElement('button');
    btn.textContent = AuthAPI.MESSAGES.RECONNECT;
    btn.onclick = function () { AuthAPI.reconnect(undefined, currentAppState()); };
    error.appendChild(msg);
    error.appendChild(btn);
    error.style.display = 'block';
}

// The pre-flight every write goes through. Returns true when a valid token
// is in hand and the caller may proceed. Returns false after parking
// `pending` and starting a renewal (or, when only an interactive sign-in
// can help, after showing the reconnect prompt with the edit still parked
// so it replays once the user signs back in).
function ensureTokenBeforeWrite(pending) {
    if (!AuthAPI) return true; // no auth layer (node --test) — nothing to check
    if (AuthAPI.getValidToken()) return true;

    queuePendingWrite(pending);

    if (!AuthAPI.needsReconnect()) {
        var result = AuthAPI.handleAuthFailure(undefined, currentAppState());
        if (result && result.status === 'redirecting') return false; // navigating now
    }

    renderReconnectPrompt();
    return false;
}

// Backstop for the race the pre-flight cannot cover: the token was still
// valid when the PUT left, and Google rejected it anyway (401/403, or a
// revoked session). sheets.js already invoked the auth failure handler, so
// all that's left is to park the edit for replay and — when no redirect is
// under way — show the reconnect prompt. Returns true when it owned the
// error, i.e. the caller must NOT alert.
function handleWriteAuthFailure(err, pending) {
    if (!err || !err.authRequired) return false;
    queuePendingWrite(pending);
    if (!(err.authResult && err.authResult.status === 'redirecting')) {
        renderReconnectPrompt();
    }
    return true;
}

// Replays whatever the last expiry parked, oldest first. Called on load
// once a valid token is in hand and BEFORE the network read, so the
// re-render shows the replayed values. Anything that fails again stays
// queued for the next attempt.
async function flushPendingWrites() {
    var list = readPendingWrites();
    if (!list.length || !sheetsClient) return 0;

    writePendingWrites([]); // take them off first, re-park only real failures

    var failed = [];
    for (const write of list) {
        try {
            if (write.kind === 'rpe') {
                await sheetsClient.updateRPE(write.sheetName, write.rowIndex, write.value);
            } else {
                await sheetsClient.updateCell(write.sheetName, write.rowIndex, write.colIndex, write.value);
            }
        } catch (e) {
            console.error('Pending write replay failed', write, e);
            failed.push(write);
        }
    }
    if (failed.length) writePendingWrites(failed);
    return list.length - failed.length;
}

// injectPastComments — JS port of server.py's inject_past_exercise_comments
// (server.py:1571-1691, read with sed per H2, never imported). Same
// indexing ({dayNum: {lower(name): [entries]}}), same match priority (exact
// sets+reps, heaviest on ties; else heaviest same-name entry in that JOUR),
// same "Passé: {sets}x{reps} @{load}kg RPE {rpe}" prefix prepended into
// column R (index 17, row padded to 18 cells), same "already has a Passé:"
// skip, same RPE-perçu-falls-back-to-donné rule, same "\n\n" separator.
// server.py only ever calls this with (current_tab, past_tab) — never the
// reverse — for the /ws2/entrainement/data response; this file calls it the
// same way, on the same two tabs.
//
// ONE deliberate divergence from server.py (bug fix, see fuseSets below):
// both passes now carry a merged "Séries" cell (column K) down its exercise
// group, exactly as parseDays does. server.py required a literal non-empty
// K on both sides, which silently dropped the "Passé: ..." line for every
// exercise but the first of a merged group.
function injectPastComments(currentData, pastData) {
    if (!currentData || !currentData.values || !pastData || !pastData.values) {
        return currentData;
    }

    var currentValues = currentData.values;
    var pastValues = pastData.values;

    // Mirrors Python's `str(row[idx]).strip()` for a row that may be
    // shorter than idx (ragged rows from the Sheets API): Python's
    // `len(row) > idx` guard, else "".
    function cellStr(row, idx) {
        if (row.length > idx) {
            var v = row[idx];
            return (v === null || v === undefined) ? '' : String(v).trim();
        }
        return '';
    }

    // Mirrors parse_load_value: strip everything but digits/./, , replace
    // ',' with '.', float() it — but Python's float() raises (caught ->
    // -1.0) on things like "1.2.3" (two dots) where JS's lenient
    // parseFloat("1.2.3") would silently return 1.2. This regex enforces
    // "at most one dot" so the two languages agree on every input.
    function parseLoadValue(loadStr) {
        if (!loadStr) return -1.0;
        var s = String(loadStr);
        var clean = '';
        for (var i = 0; i < s.length; i++) {
            var c = s.charAt(i);
            if ((c >= '0' && c <= '9') || c === '.' || c === ',') clean += c;
        }
        var normalized = clean.replace(/,/g, '.');
        if (normalized === '' || normalized === '.' || !/^\d*\.?\d*$/.test(normalized)) return -1.0;
        var f = parseFloat(normalized);
        return isNaN(f) ? -1.0 : f;
    }

    // Python's max(list, key=...) keeps the FIRST element on a tie (it only
    // replaces on strictly-greater). Mirrored here with a plain scan rather
    // than Array.reduce to keep that first-wins-ties behaviour obvious.
    function heaviest(list) {
        var best = list[0];
        for (var i = 1; i < list.length; i++) {
            if (list[i].load_val > best.load_val) best = list[i];
        }
        return best;
    }

    // The one row-is-an-exercise test, shared by both passes below. Same
    // rule server.py used inline: a non-empty column G that is neither the
    // "EXERCICE" header nor a "JOUR ..." banner.
    function isExerciseName(name) {
        return !!name && name.toUpperCase() !== 'EXERCICE' && name.toUpperCase().indexOf('JOUR') === -1;
    }

    // Merged "Séries" cells: the sheet fuses column K down an exercise
    // group, so only the FIRST row of the group carries a value. parseDays
    // already compensates ("Handle Merged Sets Cells (Fusion logic)"), but
    // server.py's injector did not — it required a non-empty column K on
    // both sides, so every exercise after the first in a merged group was
    // neither indexed from the past week nor injected into the current one,
    // and its "Passé: ..." line silently never appeared. This mirrors
    // parseDays' rules exactly: carry the last value over a blank K on a
    // real exercise row, reset on a row with no name (and, at the call
    // sites, on every new JOUR).
    function fuseSets(name, sets, state) {
        if (isExerciseName(name)) {
            if (sets) state.lastSets = sets;
            else if (state.lastSets) return state.lastSets;
        } else if (!name) {
            state.lastSets = null;
        }
        return sets;
    }

    // 1. Map past exercises by Day Number -> Name -> List of entries
    var pastMap = {};
    var currentPastDay = null;

    var pastSets = { lastSets: null };

    pastValues.forEach(function (row) {
        if (row.length > 2) {
            var val = cellStr(row, 2).toUpperCase();
            if (val.indexOf('JOUR') !== -1) {
                var match = /JOUR\s*(\d+)/.exec(val);
                if (match) {
                    currentPastDay = parseInt(match[1], 10);
                    if (!(currentPastDay in pastMap)) pastMap[currentPastDay] = {};
                    pastSets.lastSets = null; // new day — never carry across
                }
            }
        }

        if (currentPastDay === null) return;

        var name = cellStr(row, 6);
        var sets = fuseSets(name, cellStr(row, 10), pastSets);

        if (isExerciseName(name) && sets) {
            var normName = name.toLowerCase();
            var reps = cellStr(row, 11);
            var load = cellStr(row, 13);

            // RPE: prefer perçu (O=14), fall back to donné (M=12)
            var rpe = cellStr(row, 14);
            if (!rpe) rpe = cellStr(row, 12);

            var entry = {
                sets: sets,
                reps: reps,
                load: load,
                rpe: rpe,
                load_val: parseLoadValue(load)
            };

            if (!(normName in pastMap[currentPastDay])) pastMap[currentPastDay][normName] = [];
            pastMap[currentPastDay][normName].push(entry);
        }
    });

    // 2. Iterate current values and inject
    var currentDayNum = null;
    var currentSets = { lastSets: null };

    currentValues.forEach(function (row) {
        if (row.length > 2) {
            var val = cellStr(row, 2).toUpperCase();
            if (val.indexOf('JOUR') !== -1) {
                var match = /JOUR\s*(\d+)/.exec(val);
                if (match) {
                    currentDayNum = parseInt(match[1], 10);
                    currentSets.lastSets = null; // new day — never carry across
                }
            }
        }

        if (currentDayNum === null) return;

        var name = cellStr(row, 6);
        var sets = fuseSets(name, cellStr(row, 10), currentSets);

        if (isExerciseName(name) && sets) {
            var reps = cellStr(row, 11);
            var normName = name.toLowerCase();

            var dayExercises = pastMap[currentDayNum] || {};
            var candidates = dayExercises[normName] || [];

            var selectedPast = null;

            if (candidates.length > 0) {
                // Priority 1: Exact Sets AND Reps match
                var exactMatches = candidates.filter(function (c) {
                    return c.sets === sets && c.reps === reps;
                });

                if (exactMatches.length > 0) {
                    selectedPast = heaviest(exactMatches);
                } else {
                    // Priority 2: same name, same day, heaviest
                    selectedPast = heaviest(candidates);
                }
            }

            if (selectedPast) {
                var pastStr = 'Passé: ' + selectedPast.sets + 'x' + selectedPast.reps +
                    ' @' + selectedPast.load + 'kg RPE ' + selectedPast.rpe;

                // Ensure column R (17) exists
                while (row.length < 18) row.push('');

                var currentComment = cellStr(row, 17);

                // Prepend if not already present
                if (currentComment.indexOf('Passé:') === -1) {
                    if (currentComment) {
                        row[17] = pastStr + '\n\n' + currentComment;
                    } else {
                        row[17] = pastStr;
                    }
                }
            }
        }
    });

    return currentData;
}

// switchTab — academia.html:531-547, one enumerated change: the
// `historico` (Perfs) branch is dropped, nothing else touched.
function switchTab(viewId, element) {
    // Update Tab styles
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    element.classList.add('active');
    
    // Update View visibility
    document.querySelectorAll('.view-section').forEach(v => v.classList.remove('active'));
    document.getElementById(viewId + '-view').classList.add('active');

    if (viewId === 'passados') {
        loadPastData();
    } else if (viewId === 'futuros') {
        loadFutureData();
    }
}

// pastDataLoaded — academia.html:549 (`let pastDataLoaded = false;`). Not
// covered by any H1 table range (it sits between switchTab and
// loadFutureData, alongside the now-deleted chartsLoaded/allChartData
// charts state), but it's read/written by loadPastData below and would
// throw a ReferenceError if dropped. Kept; chartsLoaded/allChartData were
// charts-only and are not.
let pastDataLoaded = false;

// nextWeekCache — memoises the next-week sheet loadFutureData fetches, so
// switching to "À venir" repeatedly costs one network call, not one per
// switch. Reset next to pastDataLoaded whenever a completed day changes what
// the other tabs must show. Shape: {title, data}.
let nextWeekCache = null;

// Heading that separates the next-week block from the rest of this week's
// remaining days, so the two never read as one continuous list.
function appendWeekHeading(container, label) {
    const heading = document.createElement('h2');
    heading.style.cssText = 'margin: 24px 0 4px 0; color: #888; text-transform: uppercase; font-size: 0.8em; letter-spacing: 1px;';
    heading.textContent = label;
    container.appendChild(heading);
}

// loadFutureData — academia.html:553-581, one change: the tab no longer stops
// at the end of the current sheet.
//
// It only ever listed the days left in the CURRENT week, which meant it went
// empty on the last day of a week — exactly when "what's coming up" is the
// thing you actually want to see. It now appends next week's sheet (the one
// resolveWeekTabs declined to promote, window.nextTitle) under its own
// heading. Days already carrying a fatigue value are filtered out of both
// blocks, same rule as before.
        async function loadFutureData() {
            const content = document.getElementById('content-futuros');
            content.innerHTML = '';

            if (!window.currentData || !window.currentData.values) {
                content.innerHTML = '<p class="no-data">Données non chargées. Essayez d\'actualiser.</p>';
                return;
            }

            const days = parseDays(window.currentData.values, window.currentData.sheet_name);
            const activeDays = days.filter(d => d.exercises.length > 0);

            // Find index of current workout (first one without fatigue value)
            const currentIndex = activeDays.findIndex(d => !d.hasFatigueValue);
            
            let futureDays = [];
            if (currentIndex !== -1) {
                // Get all days AFTER the current one
                // And explicitly filter for those without fatigue (as per requirements, though implied by logic)
                futureDays = activeDays.slice(currentIndex + 1).filter(d => !d.hasFatigueValue);
            }

            let rendered = false;
            if (futureDays.length > 0) {
                renderDaysList(futureDays, 'content-futuros', true, true);
                rendered = true;
            }

            // Next week's sheet, when one exists and hasn't been promoted yet.
            const nextTitle = (typeof window !== 'undefined') ? window.nextTitle : null;
            if (nextTitle) {
                try {
                    if (!nextWeekCache || nextWeekCache.title !== nextTitle) {
                        nextWeekCache = { title: nextTitle, data: await sheetsClient.getTab(nextTitle) };
                    }
                    const nextData = nextWeekCache.data;
                    const nextDays = parseDays(nextData.values, nextData.sheet_name)
                        .filter(d => d.exercises.length > 0 && !d.hasFatigueValue);

                    if (nextDays.length > 0) {
                        appendWeekHeading(content, 'Semaine prochaine — ' + nextData.sheet_name);
                        renderDaysList(nextDays, 'content-futuros', true, true);
                        rendered = true;
                    }
                } catch (err) {
                    // A failed fetch must not wipe the days already rendered
                    // above; show the error only when there is nothing else.
                    console.error('Error fetching next week data:', err);
                    if (!rendered) {
                        content.innerHTML = '<p class="no-data">Erreur lors du chargement de la semaine prochaine : ' + err.message + '</p>';
                        return;
                    }
                }
            }

            if (!rendered) {
                content.innerHTML = '<p class="no-data">Pas encore d\'entraînements à venir.</p>';
            }
        }

// loadPastData — academia.html:583-650, two enumerated changes:
//   1. the fetch(buildApiUrl('/ws2/entrainement/past_data')) call
//      (Response.ok/.json handling included, since that's the fetch
//      mechanics being replaced) is swapped for sheetsClient.getPastTab(),
//      which returns the parsed {sheet_name, values} directly and throws
//      instead of returning {error: ...}.
//   2. the "rolling window" is dropped (bug fix). It used to slice the
//      first `currentCompletedDays.length` days off the FRONT of the
//      previous week so the tab always held a fixed number of days, which
//      meant last week's workouts disappeared one by one as this week
//      progressed. The tab now shows every day of the previous week sheet
//      plus every already-completed day of the current week.
        async function loadPastData() {
            if (pastDataLoaded) return;
            
            const loading = document.getElementById('loading-passados');
            const error = document.getElementById('error-passados');
            const content = document.getElementById('content-passados');
            
            loading.style.display = 'block';
            content.innerHTML = '';
            error.style.display = 'none';

            try {
                // 1. Fetch Previous Week Data
                // The past sheet is whichever one resolveWeekTabs put behind the
                // current week — not blindly index -2, which is the wrong sheet
                // whenever the window has slid back onto an unfinished week.
                // window.pastTitle is undefined only when no load has resolved a
                // window yet; null means "resolved, and there is no older sheet"
                // (don't fall back to getPastTab() there — index -2 would be the
                // current week itself).
                const resolvedPastTitle = (typeof window !== 'undefined') ? window.pastTitle : undefined;
                let pastDataRaw = null;
                if (resolvedPastTitle) {
                    pastDataRaw = await sheetsClient.getTab(resolvedPastTitle);
                } else if (resolvedPastTitle === undefined) {
                    pastDataRaw = await sheetsClient.getPastTab();
                }

                // 2. Parse Past Data
                let pastDays = [];
                if (pastDataRaw && pastDataRaw.values) {
                    pastDays = parseDays(pastDataRaw.values, pastDataRaw.sheet_name).filter(d => d.exercises.length > 0);
                }

                // 3. Get Completed Days from Current Week
                let currentCompletedDays = [];
                if (window.currentData && window.currentData.values) {
                    const currentDays = parseDays(window.currentData.values, window.currentData.sheet_name);
                    currentCompletedDays = currentDays.filter(d => d.exercises.length > 0 && d.hasFatigueValue);
                }

                // 4. Combine — the WHOLE previous week, then this week's
                // completed days appended in sheet order. No trimming: every
                // day of the previous week stays visible all week long.
                const daysToShow = [...pastDays, ...currentCompletedDays];

                if (daysToShow.length === 0) {
                    content.innerHTML = '<p class="no-data">Aucun entraînement passé trouvé.</p>';
                } else {
                    renderDaysList(daysToShow, 'content-passados', false); // isReadOnly = false (Editable!)
                }

                pastDataLoaded = true;

            } catch (err) {
                console.error('Error fetching past data:', err);
                error.textContent = 'Erreur lors du chargement des entraînements passé : ' + err.message;
                error.style.display = 'block';
            } finally {
                loading.style.display = 'none';
            }
        }


// window.sheetName = '' — academia.html:652. Not covered by any H1 table
// range (sits between loadPastData and toggleSettings), but parseDays/
// renderDay fall back to it (`day.sheetName || window.sheetName`). Kept,
// guarded so a node require doesn't throw on an undefined `window`.
if (typeof window !== 'undefined') {
    window.sheetName = '';
}

// toggleSettings / togglePastLoad — academia.html:654-667, one enumerated
// change: setCookie('show_past_load', ...) -> sheetsClient.setSettings
// ({showPastLoad: ...}) (localStorage, via sheets.js's settings API from
// S3). This also fixes the iOS Safari ITP 7-day script-cookie cap that made
// the toggle reset weekly on the iPhone.
// renderVersionInfo — new (no academia.html counterpart). Fills the settings
// menu's version footer.
//
// Two separate facts, because they fail independently:
//   1. CACHE_VERSION from config.js — the version of the JS that is RUNNING
//      right now. This is the one that answers "did my reload pick up the
//      deploy?", and it is bumped by hand on every release (README, "How to
//      release a new version").
//   2. The service worker's live shell cache (`entr-shell-<version>`, read
//      back from the Cache Storage API). sw.js carries its own copy of
//      CACHE_VERSION, so the two can disagree — a stale SW still serving an
//      old shell is exactly the failure this footer is meant to expose, and
//      it gets flagged in amber rather than silently ignored.
async function renderVersionInfo() {
    if (typeof document === 'undefined') return;

    const versionEl = document.getElementById('version-value');
    const swEl = document.getElementById('version-sw');
    const version = (typeof CACHE_VERSION !== 'undefined' && CACHE_VERSION) ? CACHE_VERSION : 'inconnue';

    if (versionEl) versionEl.textContent = version;
    if (!swEl) return;

    swEl.className = '';

    if (typeof caches === 'undefined' || !caches.keys) {
        swEl.textContent = 'Service worker : indisponible';
        return;
    }

    try {
        const keys = await caches.keys();
        const shellKey = keys.find(k => k.indexOf('entr-shell-') === 0);
        if (!shellKey) {
            swEl.textContent = 'Service worker : pas encore installé';
            return;
        }
        const swVersion = shellKey.slice('entr-shell-'.length);
        if (swVersion === version) {
            swEl.textContent = 'Service worker : à jour';
        } else {
            swEl.className = 'stale';
            swEl.textContent = 'Service worker : ' + swVersion + ' (obsolète — rechargez)';
        }
    } catch (e) {
        console.warn('Version info unavailable:', e);
        swEl.textContent = 'Service worker : inconnu';
    }
}

function toggleSettings() {
    const menu = document.getElementById('settings-menu');
    menu.classList.toggle('active');
}

function togglePastLoad(checkbox) {
    if (checkbox.checked) {
        document.body.classList.add('show-past-load');
        sheetsClient.setSettings({ showPastLoad: true });
    } else {
        document.body.classList.remove('show-past-load');
        sheetsClient.setSettings({ showPastLoad: false });
    }
}

// Close settings when clicking outside — academia.html:669-676. Not
// covered by any H1 table range (sits between togglePastLoad and
// refreshCache). Kept verbatim, guarded so a node require doesn't throw on
// an undefined `document`.
if (typeof document !== 'undefined') {
    document.addEventListener('click', function(event) {
        const menu = document.getElementById('settings-menu');
        const btn = document.getElementById('settingsBtn');
        if (!menu.contains(event.target) && !btn.contains(event.target)) {
            menu.classList.remove('active');
        }
    });
}

// refreshCache — rewrite (transport change, academia.html:678-729). The SBD
// Charts half of the parallel fetch is dropped (Perfs is gone). What
// remains is functionally identical to before: clear the local tab cache,
// then reload the page — the DOMContentLoaded handler below re-fetches from
// the network on load, so a stale-cache reload always shows fresh data,
// exactly like the old server-refresh-then-reload did. Same button icon,
// same disabled+spinner-dots state, same catch/alert with the same French
// text.
async function refreshCache() {
    const btn = document.getElementById('refreshBtn');
    if (!btn) return;

    const originalContent = btn.innerHTML;
    btn.disabled = true;
    btn.innerHTML = '<span style="font-size:1.5em; line-height:0;">...</span>';

    try {
        sheetsClient.clearCache();
        location.reload();
    } catch (e) {
        console.error(e);
        alert('Erreur lors de la mise à jour du cache: ' + e.message);
        btn.disabled = false;
        btn.innerHTML = originalContent;
    }
}

// DOMContentLoaded handler — rewrite (academia.html:731-811). Same visible
// shape (loading -> content, same error div, same "Chargement des
// données..." starting text from index.html), but:
//   - pollForFreshData is dropped entirely (plan §Architecture: "background
//     fetch re-renders in place" replaces server polling — there's no
//     longer a server-side cache to poll).
//   - the old app always had a server-held credential, so it never had an
//     auth boundary; this one does. Auth.handleRedirect() consumes an
//     OAuth hash if we just came back from Google. If there's still no
//     valid token, one silent (prompt=none) redirect is attempted UNLESS
//     Auth.needsReconnect() is already true (that flag is set by
//     handleRedirect when a previous silent attempt came back
//     interaction_required) — that's what stops this from looping between
//     this page and Google's error redirect.
//   - cache-first render: if a cached current+past tab exist, render them
//     immediately (via injectPastComments, same as the network path) before
//     the network call resolves, exactly matching sheets.js's cache-first/
//     background-refetch design in the plan.
//   - a network failure after a successful cache render shows "Hors ligne —
//     données du cache" without hiding the already-rendered cached workout
//     (plan Verification #7: "an edit shows a clear failure, not a silent
//     loss", not the read path). A network failure with nothing cached
//     falls back to the original French error string, unchanged:
//     'Erreur lors du chargement des données : ' + err.message.

// resolveWeekTabs — new (no academia.html counterpart). The old code always
// treated the LAST qualifying sheet as "this week" and the one before it as
// "past". That's wrong the moment the next week's sheet exists but the
// current one still has unfinished days: the training tab jumped straight to
// JOUR 1 of the new sheet while the user was still mid-week.
//
// The rule now: the newest sheet only becomes current once it has actually
// been STARTED (at least one day with a fatigue value). Until then, if the
// previous sheet still has an unfinished day, that previous sheet stays
// current and the window slides back one (past becomes the sheet before it).
//
// `fetchTab(title)` returns the {sheet_name, values} tab or null/undefined
// when it isn't available (the cache-first path passes a cache lookup, which
// can miss). A missing tab simply leaves the default -1/-2 pair in place.
function weekActiveDays(data) {
    if (!data || !data.values) return [];
    return parseDays(data.values, data.sheet_name).filter(d => d.exercises.length > 0);
}

function weekIsStarted(data) {
    return weekActiveDays(data).some(d => d.hasFatigueValue);
}

function weekHasUnfinishedDay(data) {
    return weekActiveDays(data).some(d => !d.hasFatigueValue);
}

async function resolveWeekTabs(titles, fetchTab) {
    const lastTitle = titles[titles.length - 1];
    const prevTitle = titles.length > 1 ? titles[titles.length - 2] : null;

    const lastTab = await fetchTab(lastTitle);
    const prevTab = prevTitle ? await fetchTab(prevTitle) : null;

    if (lastTab && prevTab && !weekIsStarted(lastTab) && weekHasUnfinishedDay(prevTab)) {
        const olderTitle = titles.length > 2 ? titles[titles.length - 3] : null;
        return {
            currentTitle: prevTitle,
            currentTab: prevTab,
            pastTitle: olderTitle,
            pastTab: olderTitle ? await fetchTab(olderTitle) : null,
            // The sheet we deliberately did NOT promote — that's next week,
            // and it's what the "À venir" tab shows once this week runs out.
            nextTitle: lastTitle
        };
    }

    return {
        currentTitle: lastTitle,
        currentTab: lastTab,
        pastTitle: prevTitle,
        pastTab: prevTab,
        nextTitle: null
    };
}

if (typeof document !== 'undefined') {
    document.addEventListener('DOMContentLoaded', async () => {
        // Initialize Settings (localStorage via sheetsClient, not cookies)
        const showPast = !!(sheetsClient && sheetsClient.getSettings().showPastLoad);
        const checkbox = document.getElementById('showPastLoadCheckbox');
        renderVersionInfo();
        if (showPast) {
            document.body.classList.add('show-past-load');
            if (checkbox) checkbox.checked = true;
        } else {
            if (checkbox) checkbox.checked = false;
        }

        const loading = document.getElementById('loading');
        const error = document.getElementById('error');
        const content = document.getElementById('content');

        // --- Auth boundary ---
        // Consume any OAuth redirect hash first.
        const redirectResult = AuthAPI ? AuthAPI.handleRedirect() : { status: 'none' };
        if (redirectResult && redirectResult.appState) {
            restoreAppState(redirectResult.appState);
        }

        if (!AuthAPI || !AuthAPI.getValidToken()) {
            if (AuthAPI && AuthAPI.needsReconnect()) {
                // A previous silent attempt failed with interaction_required.
                // Don't redirect again automatically (that's the loop this
                // guards against) — show the reconnect button instead.
                loading.style.display = 'none';
                renderReconnectPrompt(error);
                return;
            }

            try {
                // Top-level redirect — nothing after this line runs if it
                // navigates away.
                AuthAPI.signIn({ silent: true, appState: currentAppState() });
                return;
            } catch (e) {
                console.error('Sign-in failed to start:', e);
                loading.style.display = 'none';
                if (error) {
                    error.textContent = AuthAPI.MESSAGES.SIGN_IN_REQUIRED + ' : ' + e.message;
                    error.style.display = 'block';
                }
                return;
            }
        }

        // --- Cache-first render ---
        let renderedFromCache = false;
        try {
            const cachedMeta = sheetsClient.getCachedMeta();
            if (cachedMeta && cachedMeta.workoutSheets && cachedMeta.workoutSheets.length > 0) {
                const titles = cachedMeta.workoutSheets;
                const resolved = await resolveWeekTabs(titles, t => sheetsClient.getCachedTab(t));
                const cachedCurrent = resolved.currentTab;
                if (cachedCurrent) {
                    const cachedPast = resolved.pastTab;
                    window.pastTitle = resolved.pastTitle;
                    window.nextTitle = resolved.nextTitle;
                    const dataToRender = cachedPast ? injectPastComments(cachedCurrent, cachedPast) : cachedCurrent;

                    window.sheetName = dataToRender.sheet_name;
                    window.currentData = dataToRender;
                    processAndRender(dataToRender, 'content', false, false, false);
                    loading.style.display = 'none';
                    content.style.display = 'block';
                    renderedFromCache = true;
                }
            }
        } catch (e) {
            console.error('Cache render error:', e);
        }

        // --- Replay edits parked by a token expiry ---
        // Runs before the read below so the re-render shows the values that
        // were just replayed, not the ones the sheet had before them.
        try {
            const replayed = await flushPendingWrites();
            if (replayed) console.log('Replayed ' + replayed + ' pending edit(s) after token renewal');
        } catch (e) {
            console.error('Pending write replay error:', e);
        }

        // --- Network fetch (always runs, to pick up changes made elsewhere) ---
        try {
            const titles = await sheetsClient.listWorkoutSheets();
            if (!titles || titles.length === 0) {
                throw new Error('Aucune feuille d\'entraînement trouvée.');
            }
            const resolved = await resolveWeekTabs(titles, t => sheetsClient.getTab(t));
            const currentTab = resolved.currentTab;
            const pastTab = resolved.pastTab;
            window.pastTitle = resolved.pastTitle;
            window.nextTitle = resolved.nextTitle;

            const data = pastTab ? injectPastComments(currentTab, pastTab) : currentTab;

            window.sheetName = data.sheet_name;
            window.currentData = data;
            processAndRender(data, 'content', false, false, false);
            loading.style.display = 'none';
            content.style.display = 'block';
            if (error) error.style.display = 'none';

        } catch (err) {
            console.error('Error fetching data:', err);
            if (renderedFromCache) {
                if (error) {
                    error.textContent = 'Hors ligne — données du cache';
                    error.style.display = 'block';
                }
            } else {
                loading.style.display = 'none';
                if (error) {
                    error.textContent = 'Erreur lors du chargement des données : ' + err.message;
                    error.style.display = 'block';
                }
            }
        }
    });
}

// updateRPE — rewrite (transport change, academia.html:813-862). The
// fetch('/ws2/entrainement/update_rpe', {user, sheet_name, row_index,
// rpe_value}) POST is replaced by sheetsClient.updateRPE(sheetName,
// rowIndex, value) (S3's client already applies the same numeric coercion
// server.py's pydantic layer used to apply, and write-through-patches the
// local cache). Same yellow -> green -> normal background feedback, same
// disabled-while-processing, same French alert() text exactly:
// 'Erreur lors de la mise à jour du RPE : ' + err.message — except when the
// failure is an expired token, which is now parked + renewed rather than
// alerted about (see ensureTokenBeforeWrite).
async function updateRPE(sheetName, rowIndex, value, element) {
    if (!value) return false;

    const pending = { kind: 'rpe', sheetName, rowIndex, colIndex: RPE_COL_INDEX, value };
    const originalBackground = element.style.backgroundColor;
    element.style.backgroundColor = '#4d3e00'; // Dark Yellow indicating processing
    element.disabled = true;

    // Token pre-flight: never PUT with a dead token — park the edit and
    // renew first. The element stays yellow (pending) while we redirect.
    if (!ensureTokenBeforeWrite(pending)) {
        element.disabled = false;
        return false;
    }

    try {
        await sheetsClient.updateRPE(sheetName, rowIndex, value);

        element.style.backgroundColor = '#1e3a20'; // Dark Green indicating success
        setTimeout(() => {
            element.style.backgroundColor = originalBackground;
            element.disabled = false;
        }, 1000);
        return true;

    } catch (err) {
        console.error('Error updating RPE:', err);
        if (handleWriteAuthFailure(err, pending)) {
            element.disabled = false;
            return false;
        }
        element.style.backgroundColor = '#3a1e1e'; // Dark Red indicating error
        alert('Erreur lors de la mise à jour du RPE : ' + err.message);
        element.disabled = false;
        return false;
    }
}

// updateCell — rewrite (transport change, academia.html:921-971). Same
// pattern as updateRPE: fetch('/ws2/entrainement/update_cell', {user,
// sheet_name, row_index, col_index, value}) -> sheetsClient.updateCell
// (sheetName, rowIndex, colIndex, value). Same yellow -> green -> normal
// feedback (respecting disableInput), same French alert() text exactly:
// 'Erreur lors de la mise à jour de la cellule : ' + err.message — except
// for an expired token, parked + renewed instead of alerted about.
async function updateCell(sheetName, rowIndex, colIndex, value, element, disableInput = true) {
    if (value === undefined || value === null) return false;

    const pending = { kind: 'cell', sheetName, rowIndex, colIndex, value };
    const originalBackground = element.style.backgroundColor;
    element.style.backgroundColor = '#4d3e00'; // Dark Yellow indicating processing
    if (disableInput) element.disabled = true;

    // Token pre-flight — see updateRPE.
    if (!ensureTokenBeforeWrite(pending)) {
        if (disableInput) element.disabled = false;
        return false;
    }

    try {
        await sheetsClient.updateCell(sheetName, rowIndex, colIndex, value);

        element.style.backgroundColor = '#1e3a20'; // Dark Green indicating success
        setTimeout(() => {
            element.style.backgroundColor = originalBackground;
            if (disableInput) element.disabled = false;
        }, 1000);
        return true;

    } catch (err) {
        console.error('Error updating Cell:', err);
        if (handleWriteAuthFailure(err, pending)) {
            if (disableInput) element.disabled = false;
            return false;
        }
        element.style.backgroundColor = '#3a1e1e'; // Dark Red indicating error
        alert('Erreur lors de la mise à jour de la cellule : ' + err.message);
        if (disableInput) element.disabled = false;
        return false;
    }
}

// debounce / debouncedUpdateCell — academia.html:973-986, byte-for-byte.
        // Debounce utility
        function debounce(func, wait) {
            let timeout;
            return function(...args) {
                const context = this;
                clearTimeout(timeout);
                timeout = setTimeout(() => func.apply(context, args), wait);
            };
        }

        // Debounced version of updateCell for auto-save (doesn't disable input)
        const debouncedUpdateCell = debounce((sheetName, rowIndex, colIndex, value, element) => {
            updateCell(sheetName, rowIndex, colIndex, value, element, false);
        }, 2000);


// updateFatigueCell — academia.html:988-1006, one enumerated change: the
// fetch(refresh) + location.reload() pair is replaced by a local cache
// refresh (listWorkoutSheets + getTab current/past, same call shape the
// DOMContentLoaded network path uses) + injectPastComments + a
// processAndRender re-render in place, instead of reloading the whole page.
// Same loading-message swap and same content-hidden-while-loading
// behaviour around it.
async function updateFatigueCell(sheetName, rowIndex, colIndex, value, element) {
    try {
        const written = await updateCell(sheetName, rowIndex, colIndex, value, element);
        // The write was parked for replay (expired token) or failed — the
        // sheet hasn't changed, so there is no next workout to load yet.
        if (!written) return;

        // Completing a day changes what "Passé" must show, so make the tab
        // re-fetch instead of serving the list it built earlier this session.
        pastDataLoaded = false;
        nextWeekCache = null;

        // Show loading state
        const loading = document.getElementById('loading');
        if(loading) {
            loading.style.display = 'block';
            loading.textContent = 'Mise à jour du cache et chargement du prochain entraînement...';
        }
        document.getElementById('content').style.display = 'none';

        // Refresh cache and re-render (was: fetch(refresh) + location.reload())
        const titles = await sheetsClient.listWorkoutSheets();
        const resolved = await resolveWeekTabs(titles, t => sheetsClient.getTab(t));
        const currentTab = resolved.currentTab;
        const pastTab = resolved.pastTab;
        window.pastTitle = resolved.pastTitle;
        window.nextTitle = resolved.nextTitle;

        const data = pastTab ? injectPastComments(currentTab, pastTab) : currentTab;

        window.sheetName = data.sheet_name;
        window.currentData = data;
        processAndRender(data, 'content', false, false, false);

        if (loading) loading.style.display = 'none';
        document.getElementById('content').style.display = 'block';
    } catch (e) {
        console.error("Fatigue update failed", e);
    }
}

// renderDaysList — academia.html:1008-1018, byte-for-byte.
        function renderDaysList(days, containerId, isReadOnly, hideExtras = false) {
             const content = document.getElementById(containerId);
             
             days.forEach(day => {
                 const dayHeader = document.createElement('h3');
                 dayHeader.style.cssText = 'margin: 20px 0 10px 0; color: #4dabf7; text-transform: uppercase; font-size: 0.9em; letter-spacing: 1px; border-bottom: 1px solid #333; padding-bottom: 5px;';
                 dayHeader.textContent = day.name || 'Jour Inconnu';
                 content.appendChild(dayHeader);
                 renderDay(day, content, isReadOnly, hideExtras);
             });
        }

// processAndRender — academia.html:1020-1065, one enumerated change: the
// three fetch(buildApiUrl('/ws2/entrainement/clear_cache'), {method:
// 'POST'}) calls become sheetsClient.clearCache() (synchronous, local —
// the .then/.catch logging on the "end of sheet" branch is kept as a
// try/catch around the synchronous call instead, same two console
// messages). Nothing else touched.
        function processAndRender(data, containerId = 'content', isReadOnly = false, hideExtras = false, tempReadOnly = false) {
            const content = document.getElementById(containerId);
            content.innerHTML = '';

            if (!data.values || data.values.length === 0) {
                content.innerHTML = '<p class="no-data">Aucune donnée trouvée dans la feuille.</p>';
                if (!isReadOnly) sheetsClient.clearCache();
                return;
            }

            const days = parseDays(data.values, data.sheet_name);
            // Filter days with no exercises
            const activeDays = days.filter(d => d.exercises.length > 0);

            if (isReadOnly) {
                if (activeDays.length === 0) {
                     content.innerHTML = '<p class="no-data">Aucun entraînement trouvé cette semaine.</p>';
                } else {
                     renderDaysList(activeDays, containerId, true, hideExtras);
                }
                return;
            }

            // Find first day without fatigue value
            const targetDay = activeDays.find(d => !d.hasFatigueValue);

            if (targetDay) {
                // When rendering the single active day, we might pass tempReadOnly if loading from cache
                // But generally for the main view 'isReadOnly' is false.
                renderDay(targetDay, content, tempReadOnly, hideExtras);
            } else if (activeDays.length > 0) {
                 // All days completed. Show message AND the last workout as requested.
                 content.innerHTML = '<p class="no-data" style="margin-bottom: 12px;">Tous les entraînements ont été complétés !</p>';

                 const lastDay = activeDays[activeDays.length - 1];
                 renderDay(lastDay, content, tempReadOnly, hideExtras);

                 // Clear cache because we are done with this sheet
                 try {
                    sheetsClient.clearCache();
                    console.log('Cache cleared (end of sheet)');
                 } catch (e) {
                    console.error('Error clearing cache', e);
                 }
            } else {
                 content.innerHTML = '<p class="no-data">Aucun entraînement trouvé.</p>';
                 sheetsClient.clearCache();
            }
        }


// normalizeText, getCommentCoordinates — academia.html:1067-1079,
// byte-for-byte.
        function normalizeText(text) {
            return text.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
        }

        function getCommentCoordinates(dayNum) {
            // Centralized logic for Comment Cell location
            // Column O is index 14
            // Day 1 starts at Row 23, step 15 (Day 2 = 38, etc.)
            return {
                rowIndex: 23 + (dayNum - 1) * 15,
                colIndex: 14
            };
        }

// parseDays — academia.html:1081-1297, byte-for-byte (217 lines, the
// highest-risk copy: merged-Séries carry-over, the dynamic fatigue-label
// scan, JOUR 3 -> H41, JOUR 5 -> H71). Copied whole, nothing changed.
        function parseDays(rows, sheetName) {
            const days = [];
            let currentDay = null;
            let lastExerciseRowIndex = -1;
            // Variable to track the last valid "Sets" value for merged cells
            let lastSets = null;
            const currentSheetName = sheetName || window.sheetName;

            const isValidFatigueValue = (val) => {
                if (val === null || val === undefined) return false;
                const s = val.toString().trim();
                if (s === '') return false;
                const n = parseFloat(s.replace(',', '.'));
                return !isNaN(n) && n >= 0 && n <= 10;
            };

            rows.forEach((row, rowIndex) => {
                let isExerciseRow = false;

                // Check for start of new day (JOUR X) - Column C (index 2)
                if (row[2] && typeof row[2] === 'string' && row[2].toUpperCase().includes('JOUR')) {
                    if (currentDay) {
                        days.push(currentDay);
                    }
                    currentDay = {
                        name: row[2],
                        exercises: [],
                        hasFatigueValue: false,
                        fatiguePhysique: null,
                        fatiguePsy: null,
                        fatiguePost: null,
                        comment: null,
                        sheetName: currentSheetName
                    };
                    
                    // Reset lastSets when a new day starts
                    lastSets = null;

                    // Extract Comment Data based on Day Number
                    const dayMatch = row[2].match(/JOUR\s*(\d+)/i);
                    if (dayMatch) {
                        const dayNum = parseInt(dayMatch[1]);
                        const coords = getCommentCoordinates(dayNum);
                        
                        // Check bounds (coords.rowIndex is 1-based)
                        if (rows.length >= coords.rowIndex) {
                             const dataRow = rows[coords.rowIndex - 1]; // 0-based array index
                             const commentValue = (dataRow && dataRow[coords.colIndex]) ? dataRow[coords.colIndex] : '';
                             
                             currentDay.comment = {
                                 rowIndex: coords.rowIndex,
                                 colIndex: coords.colIndex,
                                 value: commentValue
                             };
                        }
                    }
                }

                if (currentDay) {
                    // Check for Exercises
                    const exerciseName = row[6] ? row[6].toString().trim() : '';
                    let setsStr = row[10] ? row[10].toString().trim() : '';

                    // Handle Merged Sets Cells (Fusion logic)
                    if (exerciseName && exerciseName.toUpperCase() !== 'EXERCICE' && !exerciseName.toUpperCase().includes('JOUR')) {
                         if (setsStr) {
                             lastSets = setsStr;
                         } else if (lastSets) {
                             setsStr = lastSets;
                         }
                    } else if (!exerciseName) {
                        // Reset on empty rows to prevent leakage across gaps
                        lastSets = null;
                    }

                    if (exerciseName && 
                        exerciseName.toUpperCase() !== 'EXERCICE' && 
                        !exerciseName.toUpperCase().includes('JOUR') &&
                        setsStr) {
                         // Extract details
                        const sets = setsStr;
                        const safeStr = (val) => (val === null || val === undefined) ? '' : val.toString();
                        
                        const reps = safeStr(row[11]);
                        const rpeDonne = safeStr(row[12]); // RPE donné
                        const charge = safeStr(row[13]);
                        const currentRpe = safeStr(row[14]); // RPE perçu (Column O)
                        const comment = safeStr(row[17]); // Commentaire (Column R)

                        currentDay.exercises.push({
                            name: exerciseName,
                            sets: sets,
                            reps: reps,
                            rpe: rpeDonne,
                            load: charge,
                            rowIndex: rowIndex + 1, // Store 1-based row index for API
                            currentRpe: currentRpe,
                            comment: comment
                        });
                        isExerciseRow = true;
                    }

                    // ...
                    // Check for Fatigue Labels Dynamically
                    row.forEach((cell, colIndex) => {
                        if (cell && (typeof cell === 'string' || typeof cell === 'number')) {
                            const normalizedCell = normalizeText(cell.toString());
                            
                            // Helper to find value to the right (skips empty cells)
                            const findValue = (startCol, defaultOffset, searchLimit = 3) => {
                                // Search up to searchLimit cells to the right for a value
                                for (let i = 1; i <= searchLimit; i++) {
                                    const targetCol = startCol + i;
                                    const val = row[targetCol];
                                    if (val !== undefined && val !== null && val.toString().trim() !== '') {
                                        return {
                                            rowIndex: rowIndex + 1,
                                            colIndex: targetCol,
                                            value: val
                                        };
                                    }
                                }
                                // Not found, return default position (likely empty)
                                return {
                                    rowIndex: rowIndex + 1,
                                    colIndex: startCol + defaultOffset,
                                    value: null
                                };
                            };

                            // Fatigue Physique
                            if (normalizedCell.includes('fatigue physique') || normalizedCell.includes('fadiga fisica')) {
                                // User request: Always Column H (Index 7)
                                currentDay.fatiguePhysique = {
                                    rowIndex: rowIndex + 1,
                                    colIndex: 7,
                                    value: row[7]
                                };
                            } 
                            // Fatigue Psy
                            else if (normalizedCell.includes('fatigue psy') || normalizedCell.includes('fatigue mentale') || normalizedCell.includes('fatigue mental') || normalizedCell.includes('fadiga mental') || normalizedCell.includes('fadiga psy')) {
                                currentDay.fatiguePsy = findValue(colIndex, 2);
                            } 
                            // Fatigue Post-Workout
                            // Matches "niveau de fatigue après la séance", "fadiga pós-sessão", etc.
                            else if ((normalizedCell.includes('fatigue') || normalizedCell.includes('fadiga')) && 
                                     (normalizedCell.includes('apres') || normalizedCell.includes('após') || normalizedCell.includes('seance') || normalizedCell.includes('sessao') || normalizedCell.includes('pos'))) {
                                
                                // Centralized Logic: Always Column K (Index 10)
                                const val = row[10];
                                const valData = {
                                    rowIndex: rowIndex + 1,
                                    colIndex: 10,
                                    value: val
                                };

                                currentDay.fatiguePost = valData;
                                
                                // Update completion status based on this value
                                if (val !== null && isValidFatigueValue(val)) {
                                    currentDay.hasFatigueValue = true;
                                    console.log(`Day ${currentDay.name} marked as done. Fatigue Post value: ${val}`);
                                } else {
                                     console.log(`Day ${currentDay.name} Post Fatigue: No valid value found in Column K.`);
                                }
                            }
                        }
                    });
                }
                
                if (isExerciseRow) {
                    lastExerciseRowIndex = rowIndex;
                }
            });

            // Push the last day
            if (currentDay) {
                days.push(currentDay);
            }

            // Fix for Day 3 Physical Fatigue and Post-Workout
            const day3 = days.find(d => d.name && d.name.toUpperCase().includes('JOUR 3'));
            if (day3) {
                 // Physical Fatigue (Correct is H41)
                 const overrideRowIndex = 41; // 1-based
                 const overrideColIndex = 7;  // 0-based (H)
                 
                 // Ensure we have the data
                 if (rows.length >= overrideRowIndex) {
                     const val = rows[overrideRowIndex - 1][overrideColIndex];
                     day3.fatiguePhysique = {
                         rowIndex: overrideRowIndex,
                         colIndex: overrideColIndex,
                         value: val
                     };
                 }
            }

            // Fix for Day 5 Post-Workout Fatigue (User reported mapping error, correct is K83)
            const day5 = days.find(d => d.name && d.name.toUpperCase().includes('JOUR 5'));
            if (day5) {
                 // Physical Fatigue (Correct is H71)
                 const overrideRowIndex = 71; // 1-based
                 const overrideColIndex = 7;  // 0-based (H)
                 
                 if (rows.length >= overrideRowIndex) {
                     const val = rows[overrideRowIndex - 1][overrideColIndex];
                     day5.fatiguePhysique = {
                         rowIndex: overrideRowIndex,
                         colIndex: overrideColIndex,
                         value: val
                     };
                 }
            }

            return days;
        }

// renderDay — academia.html:1299-1486, byte-for-byte (inline styles and
// template literals included).
        function renderDay(day, container, isReadOnly = false, hideExtras = false) {
            // Render Cards Container
            const cardsContainer = document.createElement('div');
            cardsContainer.className = 'cards-container';
            const sheetName = day.sheetName || window.sheetName;
            
            // Render Exercises
            day.exercises.forEach(ex => {
                const card = document.createElement('div');
                card.className = 'exercise-card';

                let detailsHtml = `
                    <div class="detail-item">
                        <span class="detail-label">Séries</span>
                        <span class="detail-value highlight">${ex.sets}</span>
                    </div>
                    <div class="detail-item">
                        <span class="detail-label">reps</span>
                        <span class="detail-value highlight">${ex.reps}</span>
                    </div>
                `;

                if (ex.rpe && ex.rpe.trim() !== '') {
                    // Scenario: Target RPE (RPE Alvo) is provided.
                    // 1. Carga as Input or Text
                    detailsHtml += `<div class="detail-item"><span class="detail-label">Charge</span>`;
                    
                    if (isReadOnly) {
                        detailsHtml += `<span class="detail-value">${ex.load || '-'}</span>`;
                    } else {
                        // Temp readonly for cache loading
                        const disabledAttr = ''; // Should be passed if we want temp disable
                        const disabledStyle = '';
                         detailsHtml += `
                            <input type="text" class="rpe-select"
                                   style="width: 60px; text-align: center; ${disabledStyle}"
                                   value="${ex.load || ''}"
                                   ${disabledAttr}
                                   oninput="debouncedUpdateCell('${sheetName}', ${ex.rowIndex}, 13, this.value, this)"
                                   onchange="updateCell('${sheetName}', ${ex.rowIndex}, 13, this.value, this)" />
                        `;
                    }
                    detailsHtml += `</div>`;

                    // 2. Show RPE (Alvo) as just "RPE" (Read-only output)
                    detailsHtml += `
                        <div class="detail-item">
                            <span class="detail-label">RPE</span>
                            <span class="detail-value">${ex.rpe}</span>
                        </div>
                    `;
                } else {
                    // Scenario: No Target RPE provided (Standard behavior)
                    if (ex.load && ex.load.trim() !== '') {
                        detailsHtml += `
                            <div class="detail-item">
                                <span class="detail-label">Charge</span>
                                <span class="detail-value">${ex.load}</span>
                            </div>
                        `;

                        // RPE Selection
                        detailsHtml += `<div class="detail-item"><span class="detail-label">RPE</span>`;
                        
                        if (isReadOnly) {
                            detailsHtml += `<span class="detail-value">${ex.currentRpe || '-'}</span>`;
                        } else {
                             let optionsHtml = '<option value="">Sél...</option>';
                            for (let val = 6; val <= 10; val += 0.5) {
                                const selected = (ex.currentRpe && parseFloat(ex.currentRpe.replace(',','.')) === val) ? 'selected' : '';
                                optionsHtml += `<option value="${val}" ${selected}>${val}</option>`;
                            }
                            detailsHtml += `
                                <select class="rpe-select" onchange="updateRPE('${sheetName}', ${ex.rowIndex}, this.value, this)">
                                    ${optionsHtml}
                                </select>
                            `;
                        }
                        detailsHtml += `</div>`;
                    }
                }

                if (ex.comment && ex.comment.trim() !== '') {
                    // Check for "Passé:" line
                    let commentHtml = '';
                    let rawComment = ex.comment.trim();
                    let pastLine = '';
                    let userComment = rawComment;

                    if (rawComment.startsWith('Passé:')) {
                        const parts = rawComment.split('\n');
                        pastLine = parts[0]; // The first line is the auto-generated past info
                        userComment = parts.slice(1).join('\n').trim(); // The rest is user comment
                    }

                    if (pastLine) {
                         commentHtml += `<div class="past-perf-line">${pastLine}</div>`;
                    }
                    
                    if (userComment) {
                        commentHtml += `<div class="user-comment-line">${userComment}</div>`;
                    }
                    
                    detailsHtml += commentHtml;
                }

                card.innerHTML = `
                    <div class="exercise-name">${ex.name}</div>
                    <div class="exercise-details" style="flex-wrap: wrap;">
                        ${detailsHtml}
                    </div>
                `;

                cardsContainer.appendChild(card);
            });

            // Render Fatigue Card (After Exercises)
            if (!hideExtras && (day.fatiguePhysique || day.fatiguePsy || day.fatiguePost)) {
                const fatigueCard = document.createElement('div');
                fatigueCard.className = 'exercise-card';
                fatigueCard.style.borderLeft = '4px solid #9c27b0'; // Purple

                let fatigueHtml = `<div class="exercise-name">Fatigue</div><div class="exercise-details">`;

                const renderFatigueInput = (label, data, isPostWorkout = false) => {
                    if (!data) return '';
                    
                    let content = `<div class="detail-item"><span class="detail-label">${label}</span>`;
                    
                    if (isReadOnly) {
                         content += `<span class="detail-value">${data.value || '-'}</span>`;
                    } else {
                        let options = '<option value="">Sél...</option>';
                        for (let i = 1; i <= 10; i++) {
                            const selected = (data.value && parseInt(data.value) == i) ? 'selected' : '';
                            options += `<option value="${i}" ${selected}>${i}</option>`;
                        }
                        const updateFn = isPostWorkout ? 'updateFatigueCell' : 'updateCell';
                        
                        content += `
                            <select class="rpe-select" onchange="${updateFn}('${sheetName}', ${data.rowIndex}, ${data.colIndex}, this.value, this)">
                                ${options}
                            </select>
                        `;
                    }
                    content += `</div>`;
                    return content;
                };

                fatigueHtml += renderFatigueInput('Physique', day.fatiguePhysique);
                fatigueHtml += renderFatigueInput('Mentale', day.fatiguePsy);
                fatigueHtml += renderFatigueInput('Post-Entraînement', day.fatiguePost, true);

                fatigueHtml += `</div>`;
                fatigueCard.innerHTML = fatigueHtml;
                cardsContainer.appendChild(fatigueCard);
            }

            // Render Comment Card
            if (!hideExtras && day.comment) {
                const commentCard = document.createElement('div');
                commentCard.className = 'exercise-card';

                let commentContent = '';
                if (isReadOnly) {
                     commentContent = `<div style="width: 100%; min-height: 40px; background: transparent; color: #e0e0e0; padding: 10px; font-style: italic;">${day.comment.value || 'Aucun commentaire.'}</div>`;
                } else {
                     commentContent = `
                        <textarea
                            style="width: 100%; min-height: 80px; background: #2a2a2a; border: 1px solid #444; color: #e0e0e0; padding: 10px; border-radius: 4px; resize: vertical; font-family: inherit; font-size: 1em; box-sizing: border-box;"
                            placeholder="Écrivez vos commentaires sur l'entraînement ici..."
                            oninput="debouncedUpdateCell('${sheetName}', ${day.comment.rowIndex}, ${day.comment.colIndex}, this.value, this)"
                            onchange="updateCell('${sheetName}', ${day.comment.rowIndex}, ${day.comment.colIndex}, this.value, this)"
                        >${day.comment.value || ''}</textarea>
                    `;
                }

                commentCard.innerHTML = `
                    <div class="exercise-name">Commentaires</div>
                    <div class="exercise-details" style="display: block;">
                        ${commentContent}
                    </div>
                `;
                cardsContainer.appendChild(commentCard);
            }

            container.appendChild(cardsContainer);
        }

// node --test usage: CommonJS export tail (H3 — parseDays, injectPastComments
// and renderDay must be callable on fixture JSON with no network and no
// browser). Guarded so a plain <script> load in the browser never touches
// `module`.
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        injectPastComments,
        weekActiveDays,
        weekIsStarted,
        weekHasUnfinishedDay,
        resolveWeekTabs,
        switchTab,
        loadFutureData,
        appendWeekHeading,
        loadPastData,
        toggleSettings,
        renderVersionInfo,
        togglePastLoad,
        refreshCache,
        updateRPE,
        updateCell,
        debounce,
        debouncedUpdateCell,
        updateFatigueCell,
        renderDaysList,
        processAndRender,
        normalizeText,
        getCommentCoordinates,
        parseDays,
        renderDay,
        currentAppState,
        restoreAppState,
        readPendingWrites,
        writePendingWrites,
        queuePendingWrite,
        ensureTokenBeforeWrite,
        handleWriteAuthFailure,
        flushPendingWrites,
        renderReconnectPrompt
    };
}
